server:
  port: 9000
  servlet:
    context-path: /pshop/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia
  jpa:
    hibernate:
      ddl-auto: create
  security:
    user:
      name: user
      password: user