version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pshop
      POSTGRES_USER: pshop
      POSTGRES_PASSWORD: pshop
    ports:
      - "5432:5432"