server:
  port: 9000
  servlet:
    context-path: /api/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia
  security:
    user:
      name: user
      password: user